//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Data.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcmeErrorLog
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int CaseId { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime ExceptionDate { get; set; }
    }
}
