//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Data.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.PassengerBookings = new HashSet<PassengerBooking>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int BookingId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<decimal> BookingAmount { get; set; }
    
        public virtual Flight Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerBooking> PassengerBookings { get; set; }
    }
}
