//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Data.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class Passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger()
        {
            this.PassengerBookings = new HashSet<PassengerBooking>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int PassengerId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PassengerName => GetPassengerName();
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerBooking> PassengerBookings { get; set; }

        private string GetPassengerName()
        {
            StringBuilder sb = new StringBuilder(FirstName);
            
            if (!string.IsNullOrEmpty(MiddleName))
            {
                sb.Append($" {MiddleName}");
            }

            if (!string.IsNullOrEmpty(LastName))
            {
                sb.Append($" {LastName}");
            }

            return sb.ToString();
        }
    }
}
